$(document).ready(function(){
         $("#change").bind("input propertychange",function(){
           var tp=$("#change").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/conversion.do',
              type:"POST",
              data:{"tp":tp},
              dataType:"json",
              success:function(str){
              if(tp>=-200&&tp<=850){
                  $('#ret').val(str[0].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun"); 
              }
              if(tp>=-200&&tp<=800){
            	  $('#pret').val(str[1].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(tp>=-270&&tp<=1370){
            	  $('#kret').val(str[2].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(tp>=-210&&tp<=1200){
            	  $('#jret').val(str[3].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(tp>=-270&&tp<=400){
            	  $('#tret').val(str[4].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(tp>=-50&&tp<=1760){
            	  $('#sret').val(str[5].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(tp>=-50&&tp<=1760){
            	  $('#rret').val(str[6].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(tp>=100&&tp<=1820){
            	  $('#bret').val(str[7].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(tp>=-270&&tp<=1300){
            	  $('#nret').val(str[8].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              if(tp>=-270&&tp<=1000){
            	  $('#eret').val(str[9].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun"); 
              }
              }
           });
         });
         $("#ret").bind("input propertychange",function(){
           var ret=$("#ret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/fTemp.do',
              type:"POST",
              data:{"ret":ret},
              dataType:"json",
              success:function(str){
              if(ret>=18.52&&ret<=390.481){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[1].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[2].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[3].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[4].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[5].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[6].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[7].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[8].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              if(ret>=18.52&&ret<=390.481&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[9].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              }
              }
           });
         });
         $("#pret").bind("input propertychange",function(){
             var pret=$("#pret").val();
             $.ajax({
                url:'http://www.nanicontrol.cn/static/js/PPtTemp.do',
                type:"POST",
                data:{"pret":pret},
                dataType:"json",
                success:function(str){
                if(pret>=803.063&&pret<=2120.515){
              	  $('#change').val(str[0].value.toFixed(3));
                }else{
              	  $('#change').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-200&&str[0].value<=850){
                  $('#ret').val(str[1].value.toFixed(3));
                }else{
                  $('#ret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-270&&str[0].value<=1370){
              	  $('#kret').val(str[2].value.toFixed(3));
                }else{
              	  $('#kret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-210&&str[0].value<=1200){
              	  $('#jret').val(str[3].value.toFixed(3));
                }else{
              	  $('#jret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-270&&str[0].value<=400){
              	  $('#tret').val(str[4].value.toFixed(3));
                }else{
              	  $('#tret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-50&&str[0].value<=1760){
              	  $('#sret').val(str[5].value.toFixed(3));
                }else{
              	  $('#sret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-50&&str[0].value<=1760){
              	  $('#rret').val(str[6].value.toFixed(3));
                }else{
              	  $('#rret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=100&&str[0].value<=1820){
              	  $('#bret').val(str[7].value.toFixed(3));
                }else{
              	  $('#bret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-270&&str[0].value<=1300){
              	  $('#nret').val(str[8].value.toFixed(3));
                }else{
              	  $('#nret').val("overrun");
                }
                if(pret>=185.2008&&pret<=3757.04&&str[0].value>=-270&&str[0].value<=1000){
              	  $('#eret').val(str[9].value.toFixed(3));
                }else{
              	  $('#eret').val("overrun");
                }
                }
             });
           });
         $("#sret").bind("input propertychange",function(){
           var sret=$("#sret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/sTemp.do',
              type:"POST",
              data:{"sret":sret},
              dataType:"json",
              success:function(str){
              if(sret>=-0.2355&&sret<=18.6092){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[3].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[4].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[5].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[6].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[7].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[8].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              if(sret>=-0.2355&&sret<=18.6092&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[9].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              }
              }
           });
         });
         $("#rret").bind("input propertychange",function(){
           var rret=$("#rret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/rTemp.do',
              type:"POST",
              data:{"rret":rret},
              dataType:"json",
              success:function(str){
              if(rret>=-0.2264&&rret<=21.0026){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[3].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[4].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[5].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[6].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[7].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[8].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              if(rret>=-0.2264&&rret<=21.0026&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[9].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              }
              }
           });
         });
         $("#bret").bind("input propertychange",function(){
           var bret=$("#bret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/bTemp.do',
              type:"POST",
              data:{"bret":bret},
              dataType:"json",
              success:function(str){
              if(bret>=0.178&&bret<=13.820){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[3].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[4].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[5].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[6].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[7].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[8].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              if(bret>=0.178&&bret<=13.820&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[9].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              }
              }
           });
         });
         $("#kret").bind("input propertychange",function(){
           var kret=$("#kret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/kTemp.do',
              type:"POST",
              data:{"kret":kret},
              dataType:"json",
              success:function(str){
              if(kret>=-5.891&&kret<=54.819){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[3].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[4].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[5].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[6].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[7].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[8].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              if(kret>=-5.891&&kret<=54.819&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[9].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              }
              }
           });
         });
         $("#nret").bind("input propertychange",function(){
           var nret=$("#nret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/nTemp.do',
              type:"POST",
              data:{"nret":nret},
              dataType:"json",
              success:function(str){
              if(nret>=-3.990&&nret<=47.513){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[3].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[4].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[5].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[6].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[7].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[8].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(nret>=-3.990&&nret<=47.513&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[9].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              } 
              }
           });
         });
         $("#eret").bind("input propertychange",function(){
           var eret=$("#eret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/eTemp.do',
              type:"POST",
              data:{"eret":eret},
              dataType:"json",
              success:function(str){
              if(eret>=-8.825&&eret<=76.373){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[3].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[4].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[5].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[6].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[7].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[8].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(eret>=-8.825&&eret<=76.373&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[9].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              } 
              }
           });
         });
         $("#jret").bind("input propertychange",function(){
           var jret=$("#jret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/jTemp.do',
              type:"POST",
              data:{"jret":jret},
              dataType:"json",
              success:function(str){
              if(jret>=-8.095&&jret<=69.553){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[3].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[4].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-270&&str[0].value<=400){
            	  $('#tret').val(str[5].value.toFixed(3));
              }else{
            	  $('#tret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[6].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[7].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[8].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(jret>=-8.095&&jret<=69.553&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[9].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              }
           });
         });
         $("#tret").bind("input propertychange",function(){
           var tret=$("#tret").val();
           $.ajax({
              url:'http://www.nanicontrol.cn/static/js/tTemp.do',
              type:"POST",
              data:{"tret":tret},
              dataType:"json",
              success:function(str){
              if(tret>=-5.603&&tret<=20.872){
            	  $('#change').val(str[0].value.toFixed(3));
              }else{
            	  $('#change').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-200&&str[0].value<=850){
            	  $('#ret').val(str[1].value.toFixed(3));
              }else{
            	  $('#ret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-200&&str[0].value<=800){
            	  $('#pret').val(str[2].value.toFixed(3));
              }else{
            	  $('#pret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=100&&str[0].value<=1820){
            	  $('#bret').val(str[3].value.toFixed(3));
              }else{
            	  $('#bret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-270&&str[0].value<=1000){
            	  $('#eret').val(str[4].value.toFixed(3));
              }else{
            	  $('#eret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-210&&str[0].value<=1200){
            	  $('#jret').val(str[5].value.toFixed(3));
              }else{
            	  $('#jret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#sret').val(str[6].value.toFixed(3));
              }else{
            	  $('#sret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-50&&str[0].value<=1760){
            	  $('#rret').val(str[7].value.toFixed(3));
              }else{
            	  $('#rret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-270&&str[0].value<=1370){
            	  $('#kret').val(str[8].value.toFixed(3));
              }else{
            	  $('#kret').val("overrun");
              }
              if(tret>=-5.603&&tret<=20.872&&str[0].value>=-270&&str[0].value<=1300){
            	  $('#nret').val(str[9].value.toFixed(3));
              }else{
            	  $('#nret').val("overrun");
              }
              }
           });
         });
         $("#reset").click(function(){
           $('#change').val("");
           $('#ret').val("");
           $('#pret').val("");
           $('#kret').val("");
           $('#jret').val("");
           $('#tret').val("");
           $('#sret').val("");
           $('#rret').val("");
           $('#bret').val("");
           $('#nret').val("");
           $('#eret').val("");
         });
      });

/*Collection*/	
function AddFavorite(title,url){
try{
   window.external.addFavorite(url,title);
 }
catch(e){
 try{
    window.sidebar.addPanel(title,url,"");
  }
 catch(e){
   alert("抱歉，您所使用的浏览器无法完成此操作。\n\n请使用快捷键Ctrl+D进行收藏！");
   }
 }
}
/*end*/